package tornadocash

import (
	"context"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/ethereum/go-ethereum/crypto"
	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

var depositSelector = crypto.Keccak256([]byte("deposit(bytes32)"))[:4]

// NewDepositTool creates the tornado_deposit tool definition.
func NewDepositTool() mcp.Tool {
	return mcp.NewTool("tornado_deposit",
		mcp.WithDescription(
			"Prepare parameters for a Tornado Cash deposit. Returns pool address, ABI-encoded calldata "+
				"for deposit(bytes32), and the required msg.value in wei. "+
				"The caller must use evm_tx_info and build_evm_tx to construct and sign the actual transaction.",
		),
		mcp.WithString("chain",
			mcp.Description("EVM chain name"),
			mcp.Required(),
			mcp.Enum(SupportedChains...),
		),
		mcp.WithString("commitment",
			mcp.Description("Bytes32 Pedersen commitment (0x-prefixed, 66 chars). Generated by tornado_generate_note."),
			mcp.Required(),
		),
		mcp.WithString("denomination",
			mcp.Description("Pool denomination (e.g. \"0.1\", \"1\", \"10\", \"100\")."),
			mcp.Required(),
		),
	)
}

// HandleDeposit returns the handler for tornado_deposit.
func HandleDeposit() server.ToolHandlerFunc {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		chain, err := req.RequireString("chain")
		if err != nil {
			return mcp.NewToolResultError("chain parameter is required"), nil
		}

		commitmentHex, err := req.RequireString("commitment")
		if err != nil {
			return mcp.NewToolResultError("commitment parameter is required"), nil
		}
		commitmentBytes, err := hex.DecodeString(strings.TrimPrefix(commitmentHex, "0x"))
		if err != nil || len(commitmentBytes) != 32 {
			return mcp.NewToolResultError("commitment must be 32 bytes hex (0x-prefixed, 66 chars)"), nil
		}

		denomination, err := req.RequireString("denomination")
		if err != nil {
			return mcp.NewToolResultError("denomination parameter is required"), nil
		}

		pool, err := GetPool(chain, denomination)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		calldata := make([]byte, 4+32)
		copy(calldata[:4], depositSelector)
		copy(calldata[4:], commitmentBytes)

		result := map[string]string{
			"pool_address":       pool.Address.Hex(),
			"function_signature": "deposit(bytes32)",
			"calldata":           "0x" + hex.EncodeToString(calldata),
			"value_wei":          pool.ValueWei.String(),
			"chain":              chain,
			"denomination":       denomination,
			"token":              pool.Token,
		}
		data, err := json.Marshal(result)
		if err != nil {
			return nil, fmt.Errorf("marshal deposit params: %w", err)
		}
		return mcp.NewToolResultText(string(data)), nil
	}
}
